[package]
name = "festivalplayr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.12"
hyper = "1.3.1"
serde = "1.0.198"
serde_yaml = "0.9.34"
tokio = "1.37.0"
